### ISSUE TITLE
Can't find file on email action

### ISSUE THREAD

**Issue by acosonic** [danmunn/redmine_dmsf#1085]
`Errno::ENOENT (No such file or directory @ rb_sysopen - /tmp/dmsf_zip_20200210-66070-4bxrm.zip):
`

tmp dir is writable by all, it's "/tmp"

**Comment by acosonic** [comment]
Sending email action. File is checked, then send email clicked, but above error occurs.

**Comment by acosonic** [comment]
With 2 files

Started POST "/projects/pera/dmsf/entries/email" for 8.8.8.8 at 2020-02-10 13:24:36 +0100
Processing by DmsfController#entries_email as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3Bs/LozLh5XYnc6SgOLC56UVtNPJunpg/vUbBCaZ7B9ImJg6hjZOdxM0slj8pu9OjdqU5tKBQlZoLe17nYMWxQ==", "email"=>{"zipped_content"=>"/tmp/dmsf_zip_20200210-66070-mr6l37.zip", "folders"=>"[]", "files"=>"[7,8]", "from"=>"Me <me@gmail.com>", "reply_to"=>"", "to"=>"him@gmail.com", "cc"=>"", "subject"=>"pera dms documents", "links_only"=>"1", "public_urls"=>"1", "expired_at"=>"2020-02-13", "body"=>"test"}, "commit"=>"Send", "id"=>"pera"}
  Current user: aco (id=6)
  Rendering plugins/redmine_dmsf/app/views/dmsf_mailer/send_documents.text.erb within layouts/mailer
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/send_documents.text.erb within layouts/mailer (147.7ms)
  Rendering plugins/redmine_dmsf/app/views/dmsf_mailer/send_documents.html.erb within layouts/mailer
  Rendered plugins/redmine_dmsf/app/views/dmsf_mailer/send_documents.html.erb within layouts/mailer (8.1ms)
Completed 500 Internal Server Error in 288ms (ActiveRecord: 140.9ms)
  
Errno::ENOENT (No such file or directory @ apply2files - /tmp/dmsf_zip_20200210-66070-mr6l37.zip):

**Comment by picman** [comment]
DMSF and Redmine versions?

**Comment by acosonic** [comment]
> Environment:
>   Redmine version                4.1.0.stable.19444
>   Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
>   Rails version                  5.2.4.1
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Subversion                     1.9.3
>   Git                            2.7.4
>   Filesystem                     
> Redmine plugins:
>   redmine_dmsf                   2.4.2 devel
>   redmine_helpdesk               0.0.17
>   redmine_xapian                 2.0.1

**Comment by picman** [comment]
Hm, I can't reproduce the problem. It works fine in my case. When the email form is being opened, the selected files are zipped and stored as follows on Debian:
```
# find /tmp/ -name "dmsf_zip*" -type f
/tmp/systemd-private-6384579d246041fe9771636fce116a2d-apache2.service-4yfbaN/tmp/dmsf_zip_20200213-29663-1q05jzf.zip
```
If you click the Documents.zip link in the form, the file should be served for downloading. Please try it and also try to find the zip file in your filesystem. It should be somewhere, probably not in the expected location.

The same routine is used when you try to download multiple files or folders. Does that work?

Plugin setting _dmsf_tmpdir_ is set? Does it work if it's empty?

**Comment by acosonic** [comment]
![image](https://user-images.githubusercontent.com/862015/74426625-fbafa380-4e55-11ea-8576-51ef62f4d892.png)

**Comment by acosonic** [comment]
Downloading of zipped attachment works

http://redmine.example.com/projects/example/dmsf/entries/download_email_entries?path=%2Ftmp%2Fdmsf_zip_20200213-91536-1iypxi2.zip

**Comment by acosonic** [comment]
And I can confirm that file is there, but it gets lost upon send action...

Also files which were previously sent as link, also get lost, like something deleted them...

But only on send action (as attachment, not as link...)

**Comment by picman** [comment]
It might to be related to your email configuration. The files are sent here:

```DmsfController::entries_email```

```DmsfMailer.deliver_send_documents``` which calls ```deliver_now``` and should wait until the email is physically sent. Then I call ```File.delete```.

In your case, the file is obviously deleted before the email is sent as the email is sent asynchronously later.

My email configuration looks like follows:

```
# default configuration options for all environments
default:
  # Outgoing emails configuration (see examples above)
  email_delivery:
    delivery_method: :sendmail    
    sendmail_settings:
      arguments: -i
```

**Comment by acosonic** [comment]
My email is set like this:
```
default:
  # Outgoing emails configuration (see examples above)
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: 127.0.0.1
      port: 25
      authentication: :login
      user_name: "redmine.myserver"
      password: "redmine123"
      openssl_verify_mode: 'none
```
With properly configured DMARC, DKIM, SPF server, so that emails don't end-up in spam... Postfix signs emails with DKIM ...
