### ISSUE TITLE
Typo in config/locales/ru.yml file

### ISSUE THREAD

**Issue by jip** [danmunn/redmine_dmsf#1189]
Line 149:
```
  permission_view_dmsf_file_revision_accesses: Показывать загрзуки файлов в ленте активности
```
should be:
```
  permission_view_dmsf_file_revision_accesses: Показывать загрузки файлов в ленте активности
```

**Comment by picman** [comment]
Fixed. Thank you for reporting.

BTW, Couldn't you translate some of the not yet translated texts to Russian?

```
text_stemming_info: "This controls how the query parser will apply the stemming algorithm. The default value is
    STEM_NONE. The possible values are: STEM_NONE -  Don't perform any stemming, STEM_SOME - Search for stemmed forms
    of terms except for those which start with a capital letter, or are followed by certain characters
    (currently:'/@<>=*[{\"'), or are used with operators which need positional information. Stemmed terms are prefixed
    with 'Z', STEM_ALL - Search for stemmed forms of all words (note: no 'Z' prefix is added)."
  error_file_tmpdir_does_not_exist: "Temporary file path doesn't exist and can't be created"
  error_tmpfile_can_not_be_created: "Files can't be created in temporary file path directory"

  label_email_from_override: From
  text_email_from_override: The user currently logged in
  label_email_reply_to: Reply-to

  label_enable_cjk_ngrams: Enable generation of n-grams from CJK text
  text_enable_cjk_ngrams: "With this enabled, spans of CJK characters are split into unigrams and bigrams, with the
    unigrams carrying positional information. Non-CJK characters are split into words as normal. The corresponding
    option needs to have been used at index time.
    e.g: XAPIAN_CJK_NGRAM=true ruby plugins/redmine_dmsf/extra/xapian_indexer.rb -fv"

  label_dmsf_fast_links: Fast links
  text_dmsf_fast_links_info: You will be able to manually enter a target folder's ID when creating links in order to speed
    up the process of creating links.

  label_dmsf_permissions: Allow access only to
  label_inherited_permissions: Inherited Access for

  button_edit_content: Edit content
  field_workflow: Workflow
  field_modified: Date
  field_updated: Date
  field_count: D/L
  field_first_at: First
  field_last_at: Last
  field_size: Size

  label_add_width: Add with

  dmsf_webdav_ignore_1b_file_for_authentication: Ignore 1b file sent for authentication
  dmsf_webdav_ignore_1b_file_for_authentication_info: Total Commander WebDAV plugin

  easy_pages:
    modules:
      dmsf_locked_documents: My locked documents
      dmsf_open_approvals: My open approvals
    module_category:
      easy_dms: Easy DMS
```
