### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Atmis** [danmunn/redmine_dmsf#193]
Hello,

I don't know if there is a better way to propose a translation, but here is the french translation based on the 1.4.7 version fr.yml. It should be ok. If overtime I find a better translation for some entries, then I'll propose it.

```
 permission_manage_workflows: Gérer les flux de validation

 # Not translated

  error_unable_delete_dmsf_workflow: Impossible de supprimer le flux de validation
  error_empty_note: La note ne peut pas être vide
  error_workflow_assign: Une erreur s'est produite lors de l'attribution
  error_cannot_start_workflow: Le flux de validation ne peut pas être démarré
  error_cannot_renumber_steps: Les étapes ne peuvent pas être renumérotées
  label_dmsf_workflow_new: Nouveau flux de validation
  field_label_dmsf_workflow: Flux de validation
  field_label_dmsf_workflow_name: Nom du flux
  label_dmsf_workflow_plural: Flux de validation
  label_dmsf_workflow_step: Etape
  label_dmsf_workflow_step_plural: Etapes
  label_dmsf_workflow_approval: Approbation
  label_dmsf_workflow_approval_plural: Approbations
  label_dmsf: DMSF
  label_dmsf_wokflow_action_approve: Approuver
  label_dmsf_wokflow_action_reject: Rejeter
  label_dmsf_wokflow_action_delegate: Déléguer à
  label_dmsf_wokflow_action_assign: Attribuer un flux de validation
  label_dmsf_wokflow_action_start: Démarrer le flux de validation
  label_dmsf_workflow_add_approver: "Ajouter un nouvel approbateur avec une fonction logique :"
  label_or: ou
  label_action: Action
  label_note: Note  
  title_none: Aucun
  title_rejection: Rejet
  title_delegation: Délégation
  title_assignment: Attribution
  title_start: Démarrer  
  title_dmsf_workflow_log: Journal du flux de validation
  title_assigned: Assigné
  title_approval: Approbation
  title_rejected: Rejeté
  dmsf_and: ET
  dmsf_or: OU
  dmsf_new_step: Nouvelle étape  
  message_dmsf_wokflow_note: Votre note...
  info_revision: "r%{rev}"
  link_workflow: Flux  
  notice_workflow_started: Flux de validation démarré avec succès
  text_email_subject_approved: "Flux de validation %{name} approuvé"
  text_email_subject_rejected: "Flux de validation %{name} rejeté"
  text_email_subject_delegated: "Flux de validation %{name} délégué"
  text_email_subject_requires_approval: "Flux de validation %{name} requiert votre approbation"
  text_email_subject_updated: "Flux de validation %{name} mis à jour"
  text_email_subject_started: "Flux de validation %{name} démarré" 
  text_email_finished_approved: "Le flux de validation '%{name}' assigné au document '%{filename}' vient de se terminer et le document a été approuvé."
  text_email_finished_rejected: "Le flux de validation '%{name}' assigné au document '%{filename}' vient de se terminer et le document a été rejeté pour la raison '%{notice}'."
  text_email_finished_delegated: "Le flux de validation '%{name}' assigné au document '%{filename}' a été délégué pour la raison '%{notice}' et vous êtes tenu d'approuver l'étape actuelle."
  text_email_finished_step: "Le flux de validation '%{name}' assigné au document '%{filename}' a passé une des étapes d'approbation et vous êtes tenu d'approuver l'étape suivante."
  text_email_finished_step_short: "Le flux de validation '%{name}' assigné au document '%{filename}' a passé une des étapes d'approbation."
  text_email_started: "Le flux de validation '%{name}' assigné au document '%{filename}' vient de démarrer et vous êtes tenu d'approuver l'étape actuelle."
  text_email_to_proceed: Pour ce faire, cliquez sur l'icône de validation à côté du document dans
  text_email_to_see_history: Pour consulter l'historique de validation, cliquez sur le statut du flux du document dans
  text_email_to_see_status: Pour consulter le statut actuel du flux de validation, cliquez sur le statut du flux du document dans

  my:
    blocks:
      locked_documents: Documents verouillés
      open_approvals: Approbations en attente

  label_maximum_ajax_upload_filesize: Taille maximale de fichier pour téléversement via AJAX
  note_maximum_ajax_upload_filesize: Taille maximale, en méga octets, de fichier pour téléversement via l'interface standard AJAX. Sinon l'interface standard de Redmine doit être utilisée.
```
